### ISSUE TITLE
A puzzle about codes

### ISSUE THREAD

**Issue by Soyn** [gzc/CLRS#10]
In [Ex9.1-1](https://github.com/gzc/CLRS/blob/master/C09-Medians-and-Order-Statistics/exercise_code/second-smallest.cpp). I feel confused by this statement.
![5s86gud3q 8 oy fxd7cc8](https://cloud.githubusercontent.com/assets/7734046/9020424/10b4a380-383e-11e5-833d-e3c8abbd9f0a.png). Can you help me. Thx.

**Comment by gzc** [comment]
if root->left or root->right = minium   then root->left ^ minium or root->right ^ minium produce 0.
