### ISSUE TITLE
These solutions are not reliable

### ISSUE THREAD

**Issue by nelson-brochado** [gzc/CLRS#104]
I've just looked at the solution for one exercise about the interval trees in chapter 14, and it's wrong in my opinion. You should not share something that's not proved to be correct, it's not helpful at all!!

**Comment by gzc** [comment]
I did not claim that everything is correct. I just put my solutions here and if others find a better solution or a correct one they can pull request to me, then I will fix. Thanks.

**Comment by nelson-brochado** [comment]
@gzc It should then be your first statement in the readme and not "solutions to...".

**Comment by gzc** [comment]
Even solutions of the authors of some textbook will have wrong answers. You can not expect everything to be correct. Thanks for your understanding.

**Comment by nelson-brochado** [comment]
@gzc I can expect the solutions of well-written book to be correct. Then I need to choose the books and the authors...anyway I'm also warning students that blindly believe that these solutions are correct, just that.
