### ISSUE TITLE
23.1-11 时间复杂度问题

### ISSUE THREAD

**Issue by loverszhaokai** [gzc/CLRS#109]
https://github.com/gzc/CLRS/blob/master/C23-Minimum-Spanning-Trees/23.1.md#exercises-231-11-

该题目的思路跟作者是一样的：将权重减少的边添加回到最小生成树T中，一定会形成一个环，再将环中权重最大的边去掉。

因为题目中已经给出了G和T，所以我们只需要在环中寻找权重最大的边，最差情况下就是DFS遍历一遍T。所以时间复杂度应该是 O(V)，而不是 O(V + E)

不知道我的思路对不对，感谢查阅。

**Comment by gzc** [comment]
一般情况下认为dfs的时间复杂度是O(V+E). 当然根据数据结构的不同时间复杂度也不同. 我不太清楚你说的dfs是O(V)? 请问具体是？

**Comment by loverszhaokai** [comment]
**只遍历最小生成树T**，不要遍历G。时间复杂度就是**O(V)**。

**Comment by gzc** [comment]
如果给你另外一个单独的图T,  可以认为是O(V). 我是按在原图给edge增加flag表示新图T, 然后dfs走的时候判断flag, 所以是O(V+E).

**Comment by loverszhaokai** [comment]
是的，咱俩理解不一样。。我的理解应该比较小众，非常感谢！ 👍
