### ISSUE TITLE
Exercise 21.1-3

### ISSUE THREAD

**Issue by loverszhaokai** [gzc/CLRS#112]
https://github.com/gzc/CLRS/blob/master/C21-Data-Structures-for-Disjoint-Sets/21.1.md#exercises-211-3

> How many times is FIND-SET called?
FIND-SET : |E|

I think it should be **2\*|E|** ? Is it right ?

**Comment by gzc** [comment]
It should be **2*|E|**, thanks

**Comment by gzc** [comment]
**2*|E|**

**Comment by gzc** [comment]
it should be 2*|E|
