### ISSUE TITLE
Execise 18.1-3

### ISSUE THREAD

**Issue by meslahik** [gzc/CLRS#116]
This question is about B-Trees. The question asks for the legal trees with min degree t=2, but the solution is for t=3.
So the correct answer is 4 trees:
```
     2
  1     3 4 5
```

```
         4
  1 2 3     5
```

```
        3
  1 2      4 5
```

```
      2     4
   1     3     5
```

Although the last tree is correct according to the rules of the B-Tree, the algorithm provided by the book never generates it.

**Comment by gzc** [comment]
Hi, can you pull a request to me. Thanks ^ ^
