### ISSUE TITLE
Hard to convert chinese to english for the solution. 

### ISSUE THREAD

**Issue by jack17529** [gzc/CLRS#125]
Can someone good in both languages convert the solutions to english?

**Comment by reyhanf** [comment]
Hi,  you can use Google translate. This way, you will know what the paragraph is mainly talking about and since you know about the subject, you can guess the answer and result is ture in most cases

**Comment by jack17529** [comment]
Hey I can help to convert some solutions to english as I am myself studying the book.

**Comment by gzc** [comment]
Thanks @jack17529
