### ISSUE TITLE
Exercise 7.1-2

### ISSUE THREAD

**Issue by LiuXin11235** [gzc/CLRS#126]
I have run the code. If the input array is [2, 3, 6, 4, 6, 5, 6], the output will be [2, 3, 4, 6, 6, 5, 6]. This is obviously not right. 
Your code works rightly when all elements in the array have the same value. But when only some are the same, problems may arise.

**Comment by gzc** [comment]
Hi,

The problem says 'when all elements in the array A[p...r] have the same value.
So we can write specific algorithm to speed up the process.
