### ISSUE TITLE
A new solution about exercise11.3-2

### ISSUE THREAD

**Issue by Soyn** [gzc/CLRS#13]
**I can't get the main idea of your idea, but i google some solutions, and this one
[Answers of Ex11.3-2](http://cormensolution.blogspot.jp/2012/11/chapter-11-hash-tables.html) is appriate for this question. And i can not get the point of this paragraph**
` Another way would be using n-degree equation with each character value acting as a co-efficient for the nth term.
Example: S[0]*xn + S[1]*x(n-1)+ …. + S[n-1], for better result substitute x = 33 or 37 or 39. This is the famous Horner’s method for finding a hash value.`
**If you can figure it out. Plz tell me. Thanks a lot.**

**Comment by gzc** [comment]
I know that Horner's method is a simple and straightforward way to compute polynomials. But I didn't see the way to compute hash value. Maybe it is a method to compute hash learned by practice and experience. By the way, thank you for your link.

**Comment by gzc** [comment]
I will modify my answer

**Comment by Soyn** [comment]
Can you explain the Horner's method in Chinese. I can not get it, forgive my poor English.

**Comment by gzc** [comment]
比如ax^3+bx^2+cx+d.最笨的方法是每个单项的算式都算一遍x^k.(k = 0,1,2,3....,n). 需要O(n^2).Horner's method就是说可以先算x^1,保存下来下次用,x^2,... x^n..这样只需要O(n)

**Comment by Soyn** [comment]
这个多项式的算法我明白，我这句话不太明白 
`Another way would be using n-degree equation with each character value acting as a co-efficient for the nth term`
其中 `n-degree` 和 `co-efficient`看到我迷迷糊糊的， ps:pr了一个错误，Plz check.

**Comment by gzc** [comment]
哈,应该就是说的那个式子,我也没看明白它的意思。估计是经过积淀大家公认的方法吧 - -

**Comment by Soyn** [comment]
Thanks for your patience, you can close this issue now.
