### ISSUE TITLE
Explanation for solving 1.2.2 and 1.2.3

### ISSUE THREAD

**Issue by scriptnull** [gzc/CLRS#133]
Hi, I recently started reading this book. Its good to see this repository with solutions.

For 1.2.2 and 1.2.3, this repository contains only the final answer for it. It would be good to have the explanation of how it was arrived at. Here is what, I have reached at. Please review my method of solving this and suggest a better or good way of solving it. I will raise a PR for the explanation after getting enough feedback.

#### Exercise 1.2.2
> Suppose we are comparing implementations of insertion sort and merge sort on the same machine. For inputs of size n, insertion sort runs in ![](http://latex.codecogs.com/gif.latex?8n^2)
 steps, while merge sort runs in ![](http://latex.codecogs.com/gif.latex?64nlg{n})
 steps. For which values of n does insertion sort beat merge sort?

Insertion sort beating merge sort means,
for an input size n, time taken by insertion sort ( to give the sorted output ) should be less than the time taken by merge sort.

So, I arrived at an equation like this

![](http://latex.codecogs.com/gif.latex?8n^2) < ![](http://latex.codecogs.com/gif.latex?64nlg{n})

Figuring out all the values of n, that satisfies the above equation would give us the answer.

The equation can further be simplified, as it contains common factor, like this.
```
8n.n < 8. 8n. log n

// cancelling 8n on both sides

n < 8 log n
```
Now, I applied n=1,2,3..... on the above equation to figure out the answer as 2 < n < 43

To figure the ending point I have to manually apply the n value from 1 to 43 which is a time consuming process. So, i tried applying n values as powers of 2 ( as it would reduce the time - considering my base as 2 in log n ), this approach, helped me to arrive at a point that maximum value of n satisfies 32 < final value of n < 64. This method made me to be faster in getting the final solution. Is there method that is even faster than arriving at the answer ? 

Is this how we arrive at the answer for the exercise ? Are equations correct ? Can my equation be further reduced ? 

#### Exercise 1.2.3
I was able to arrive at an equation, similar to exercise 1.2.2. So if my above questions are being answered, then I will have a clear understanding of how this exercise is solved.

**Comment by scriptnull** [comment]
Tagging some people for help,

@Mundhey @gcz @argonlaser

Thanks for your time !

**Comment by argonlaser** [comment]
Hi @scriptnull ! We have to solve an inequality that has a logarithmic function. 
To solve this as quick as possible, we can plot the graph of ```y=n``` and ```y=8 log n``` , check their intersecting point for the solution. If we want to solve manually, we have to follow Newton-Raphson approximation method as discussed [here](https://www.math.ubc.ca/~anstee/math104/104newtonmethod.pdf). However, solving the above equation has some mathematics involved.

**Comment by Nshul** [comment]
![graph](https://cloud.githubusercontent.com/assets/26252118/26629820/bcf91854-4621-11e7-981e-576279927a06.PNG)
![grp1](https://cloud.githubusercontent.com/assets/26252118/26629821/bd0777fa-4621-11e7-8886-04e787f488ff.PNG)
![grp2](https://cloud.githubusercontent.com/assets/26252118/26629822/bd08e518-4621-11e7-8fd6-614e2b82209c.PNG)
Graph has been generated using Google
Inequalities like these are quite easily solved by observing their graph. Here it can be seen that to get n<8*lgn
we have plotted **x-8(lgn)** thus when this graph is negative we get the required values of n
hence 
**2<=n<43**
Hope this helps
