### ISSUE TITLE
Exercise 24.1-1 looks wrong

### ISSUE THREAD

**Issue by amitbansal7** [gzc/CLRS#140]
I think answer should be

~ | s | t  | x  | y | z
d | 2 | 4 | 6 | 9 | 0
π | z | x | z  | s | Ø

~ | s | t  | x  | y | z
d | 0 | 0 | 2 | 7 | -2
π | Ø | x | z  | s | t

Correct me if I'am wrong.

**Comment by gzc** [comment]
Man you are right!
Thanks so much ^ ^ I will update my solution

**Comment by amitbansal7** [comment]
Thanks :)
