### ISSUE TITLE
Exercise 2.1-4

### ISSUE THREAD

**Issue by cyberpirate92** [gzc/CLRS#147]
![](https://github.com/gzc/CLRS/blob/master/C02-Getting-Started/repo/s1/4.png?raw=true)

The loop is supposed to start from A.length isn't it?

Shouldn't it be like this?
```
C = Array[A.length+1]
carry <- 0,
for i <- A.length to 1
    C[i+1] <- (A[i] + B[i] + carry) % 2;
    carry = (A[i] + B[i] + carry)/2;
C[i+1] <- carry;
return C
```

**Comment by gzc** [comment]
@cyberpirate92 Hi you are right! Thanks for pointing it out. I will fix it soon.
