### ISSUE TITLE
关于15.4-6的代码

### ISSUE THREAD

**Issue by nbei** [gzc/CLRS#15]
能不能再给点详细的解释啊，还是对代码没有太深入的理解呢

**Comment by gzc** [comment]
比如3,4,2,1,6,5,8这个序列.

一开始是3；后来是3，4 数组长度为2；进来2,数组变成2,4；进来1，数组变成1,4; 进来6 数组变成1，4，6；进来5，变成1，5，6；进来8，变成1，5，6，8.长度为4 ～～    这只能求出长度 注意序列不是1，5，6，8；而是3，4，6，8.

**Comment by nbei** [comment]
恩  大神想再请教您一下 这个的原理是什么呢？ 怎么保证这样就是正确的呢？ 这是怎么用到那个提示的呢？

**Comment by gzc** [comment]
原理我用文字描述不好描述 0.0    你可以多举例子感受一下   不难的

**Comment by xyyimian** [comment]
> 比如3,4,2,1,6,5,8这个序列.
> 
> 一开始是3；后来是3，4 数组长度为2；进来2,数组变成2,4；进来1，数组变成1,4; 进来6 数组变成1，4，6；进来5，变成1，5，6；进来8，变成1，5，6，8.长度为4 ～～ 这只能求出长度 注意序列不是1，5，6，8；而是3，4，6，8.

我觉得不对啊....这样的话序列的顺序都打乱了啊...这已经违背子序列的定义了...最长递增子序列在原序列中的顺序不能变吧....

**Comment by xyyimian** [comment]
> 比如3,4,2,1,6,5,8这个序列.
> 
> 一开始是3；后来是3，4 数组长度为2；进来2,数组变成2,4；进来1，数组变成1,4; 进来6 数组变成1，4，6；进来5，变成1，5，6；进来8，变成1，5，6，8.长度为4 ～～ 这只能求出长度 注意序列不是1，5，6，8；而是3，4，6，8.

建议参考
http://mypathtothe4.blogspot.com/2013/02/dynamic-programming-longest-increasing.html
