### ISSUE TITLE
15.5-1的代码的小问题

### ISSUE THREAD

**Issue by nbei** [gzc/CLRS#16]
在您的代码的
void printOptimalBST(int i,int j,int r)
{
    int rootChild = root[i][j];//子树根节点
    if (rootChild == root[1][n])
    {
        //输出整棵树的根
        cout << "k" << rootChild << "是根" << endl;
        printOptimalBST(i,rootChild - 1,rootChild);
        printOptimalBST(rootChild + 1,j,rootChild);
        return;
    }
这一段，在我测试的时候出现了数组越界的情况呢，就是在输出最后一片树叶的时候，感觉是不是应该在最前面加上呢？  新手求指教！
if(i==N+1&&j==N)
{
      cout<<"d"<<j<<"is k"<<r<<" right child"<<endl;
      return ;
}

**Comment by gzc** [comment]
hello, 你解决了么？ 时间过了太久我都忘记了
