### ISSUE TITLE
Error in exercise 22.1-4

### ISSUE THREAD

**Issue by mhhacker36** [gzc/CLRS#167]
On step 3 of that given algorithm, the algo seems to add any vertex that's present in the adjacency list of the multigraph to the new adjacency list. I think what it should be doing is, **When it encounter any vertex(v) in the adj-list of u, it should check whether there is an edge (v, u), i.e. the opposite edge, and also checks if v and u are not the same**. If both the condition is true, than it should add the edge to new Graph.

My approach is based on the assumption:
- The mutligraph is implemented using adjList.
- Multi edge means (u, v) as well as (v, u), so in the adjList i'm checking for (v, u) whenever i encounter (u, v) edge.

**Comment by Sam-Jhon** [comment]
As it is specified that the graph is a multi graph it can be an undirected multigraph or a directed multigraph. Your algorithm would be true in case of undirected multi-graph

**Comment by gzc** [comment]
Thanks @mhhacker36 @tabshaikh
