### ISSUE TITLE
Broken image in chapter 2.3

### ISSUE THREAD

**Issue by RioAraki** [gzc/CLRS#182]
### Exercises 2.3-3
***
Use mathematical induction to show that when n is an exact power of 2, the solution of the recurrence
![](./repo/s3/2.png) is ![](http://latex.codecogs.com/gif.latex?T\(n\)=n\\lg{n})

1.定义 ![](http://latex.codecogs.com/gif.latex?F\(k\)=T\\(2^k\))

2.当k = 1时，![](http://latex.codecogs.com/gif.latex?F\(1\)=T\(2\)=2=2\\lg{2}=2^1\\lg{2^1})

3.假设![](http://latex.codecogs.com/gif.latex?F\(k\)=2^k\\lg{2^k})

4.![](http://latex.codecogs.com/gif.latex?F\(k+1\)=T\(2^{k+1}\)=2T(2^k\)+2^{k+1}=2*2^k\\lg{2^k}+2^{k+1}=2^{k+1}\(\\lg{2^k}+1\)=2^{k+1}\(\\lg{2^k}+\\lg{2}\)=2^{k+1}\\lg{2^{k+1}}) 

First and last image is broken, but the link works and format is correct

**Comment by dccif** [comment]
I add a pr try to fix it
https://github.com/gzc/CLRS/pull/187

**Comment by RioAraki** [comment]
cool
