### ISSUE TITLE
One question missing. Exercise 22.2-3

### ISSUE THREAD

**Issue by mhhacker36** [gzc/CLRS#208]
In exercise 22.2 (BFS) there are a total of 9 questions, but here one question is missing.
The missing question being 22.2-3.
Question is 22.2-3: Show that using a single bit to store each vertex color suffices by arguing that the BFS procedure would produce the same result if lies 5 and 14 were removed.

**Comment by gzc** [comment]
Hi @mhhacker36 I am using CLRS v2, I think that's the reason
