### ISSUE TITLE
The confuse about 14.1-5

### ISSUE THREAD

**Issue by Soyn** [gzc/CLRS#21]
The answer you post in [14.1-5](https://github.com/gzc/CLRS/blob/master/C14-Augmenting-Data-Structures/14.1.md), but i can not figure how it works. I think the follwing code is more clean than yours. [my solution](https://gist.github.com/Soyn/2e33ac9d64f1fc59cc19)

**Comment by gzc** [comment]
Yours is better, you can merge to me

**Comment by Soyn** [comment]
I will do it later.
