### ISSUE TITLE
Incorrect answer to 22.5-1

### ISSUE THREAD

**Issue by jckw** [gzc/CLRS#219]
The answer (correct me if I have misunderstood, I used google translate) suggests that if an edge is added outside of a strongly connect component, then the number of SCCs can only decrease by up to a maximum of 1. 

However, this is incorrect. A graph with n > 0 SCCs can potentially be reduced to 1 SCC by the addition of an edge, making the change a size of (n-1).

![image](https://user-images.githubusercontent.com/11884004/38196579-669f2e4c-3673-11e8-8527-dbadab91d593.png)

![image](https://user-images.githubusercontent.com/11884004/38196586-6b8d891c-3673-11e8-96f9-0dd531bfb38d.png)

The answer should therefore be: 

* If an edge is added in an SCC, the number of SCCs will remain the same. 
* If an edge is added outside of an SCC, in a graph with n > 0 SCCs, the reduction in SCCs can be between 0 and (n-1).

**Comment by gzc** [comment]
Hi @jckw , I think the google translates didn't translate well, my original idea is same as yours. BTW, can you create a pr to add English answer and the example to my answer ? Thanks so much ^_^
