### ISSUE TITLE
the problem in 14.2-3

### ISSUE THREAD

**Issue by Soyn** [gzc/CLRS#23]
I searched this problem in following URL, maybe you can check this. And i can't figure the running time more than O(nlgn) in the worst time. If you get it. Plz tell me, Thx a lot.

[Your answer on 14.2-3](https://github.com/gzc/CLRS/blob/master/C14-Augmenting-Data-Structures/14.2.md#exercises-142-3)
[Another answer](http://ripcrixalis.blog.com/2011/02/08/clrs-14-2-how-to-augment-a-data-structure/)

**Comment by gzc** [comment]
我觉得是这样的。旋转操作会改变高度，最坏情况自底向上会一直到根。

**Comment by Soyn** [comment]
我看他的意思是： 树内的节点的深度度取决于他父子节点的高度，如果x节点的高度改变那么以这个节点为根的子树的深度需要更新，需要维护的是以这个深度改变了的节点为根的子树，不一定是整个树，如果需要维护那么最坏情况下怎样得出结论其时间复杂度会超过O(nlgn).

**Comment by gzc** [comment]
我觉得他笔误吧 应该是想写O(lgn)吧

**Comment by gzc** [comment]
最坏情况应该是O(n)

**Comment by Soyn** [comment]
最坏情况下是每一个节点都需要做旋转吗？

**Comment by gzc** [comment]
嗯嗯

**Comment by gzc** [comment]
不是每一个都要做旋转

**Comment by gzc** [comment]
是一个旋转了  他儿子们的depth都变了呀
