### ISSUE TITLE
Revised answer to 13.1-6 might be wrong. 13.1-6修改后的答案可能不正确

### ISSUE THREAD

**Issue by Billijk** [gzc/CLRS#296]
PR #266 修改了13.1-6的答案，认为只有一条全黑 path 的情况下, 节点数最小, 是k。但是根据CLRS第三版的解释，如果红黑树的某个内部结点不存在，则将其指向NIL，而NIL被视为一个黑色结点。因此任何长度大于等于2的黑链在红黑树中都是违反定义的。

下图中 O 代表黑色内部结点，X 代表NIL结点。根结点到叶结点的路径中黑色结点个数可能为1或2，违反红黑树性质。

       O
     /   \
    X     O
         /  \
        X    X

**Comment by gzc** [comment]
谢谢，已经revert啦 https://github.com/gzc/CLRS/commit/cebea7730943f88c8ba5c42d264a1c9b1d7f185c
