### ISSUE TITLE
4.1的练习题答案有误

### ISSUE THREAD

**Issue by Louchenyang** [gzc/CLRS#30]
第一部分里的4.1md里面的答案跟题目对不上。
你看一下。估计是贴的别的部分的答案

ps：看了这个repo的很多题解，非常有用，感谢您的分享。

**Comment by gzc** [comment]
我看了下答案跟题目应该是一致的～

**Comment by Louchenyang** [comment]
嗯，难道书不一样么？我在后面的章节里也发现有些题目没有或者对不上的情况，请问一下您用的CLRS是第几版？我用的是第三版的中文版。

**Comment by gzc** [comment]
我4.1.1的问题就在上面呀  Show that the solution of  is O(lg n). 嗯我是第二版的.
