### ISSUE TITLE
14.2-2

### ISSUE THREAD

**Issue by xwu64** [gzc/CLRS#34]
应该不能维护吧？

当插入一个节点，递归到根节点，当根节点直接变为黑色，所有节点的黑高需要加一。 复杂度为O(n)。

**Comment by gzc** [comment]
blackheight(v) = 从v到子树中任何叶子的黑色节点的数目（如果v是黑色则不计数它，也叫做黑色高度）。不是你理解的那个黑色高度

**Comment by xwu64** [comment]
@gzc 了解了，谢谢！
