### ISSUE TITLE
The numbering of solutions in chapter 04 is wrong.

### ISSUE THREAD

**Issue by fmv1992** [gzc/CLRS#68]
The numbering of the solutions is wrong. For example, section's 4.3 exercises have nothing to do with the third edition of the book.

For example on the 3rd edition the exercise 4.3-1 is:

"Show that the solution of T(n) = T(n-1) + n is O(n * n)".

**Comment by gzc** [comment]
Sorry for it. At the very beginning, my solution is based on 2nd version of CLRS. The picture in the README is 3rd version, but the solution is based on the 2nd.
