### ISSUE TITLE
Exercise 25.1-4

### ISSUE THREAD

**Issue by ifcenens** [gzc/CLRS#80]
A brute force verification will work. Here is the proof.
[Proof of the exercise 25.1-4.pdf](https://github.com/gzc/CLRS/files/456393/Proof.of.the.exercise.25.1-4.pdf)

**Comment by gzc** [comment]
Thanks. Can you attach this link to the solution and pull a request to me? If possible, could you type the solution in markdown in case that the link is broken in the future. Anyway, both is OK to me ^_^
