### ISSUE TITLE
Exercises 7.4-5

### ISSUE THREAD

**Issue by swananan** [gzc/CLRS#86]
answer:先看快速排序的那部分，当高度为lg(n/k)便停止了快速排序。

应该是高度为lgk的时候，停止了快排。然后快排运行了lgn-lgk层，故时间复杂度应该是O(lgn/k)

**Comment by swananan** [comment]
时间复杂度应该是O(nlgn/k)，打错了- -

**Comment by gzc** [comment]
谢谢，我这有个笔误，我应该把高度改成深度
