### ISSUE TITLE
problem 8-3.b

### ISSUE THREAD

**Issue by Soyn** [gzc/CLRS#9]
Maybe you need to check your answer. I can't figure out why we need to **reverse** the string. And i can't get you.  Check at [8-3](https://github.com/gzc/CLRS/blob/master/C08-Sorting-in-Linear-Time/problem.md)

**Comment by gzc** [comment]
关于reverse.如果不先reverse,编程会复杂一点.比如对一些整数,从后面往前做 radix比较方便,如果从前面往后面扫描,首先要将0-9划分成10组做递归，随着程序的调用递归的stack可能是1->10->100->..... 所以先做reverse采用从后面往前面扫描的办法.

**Comment by Soyn** [comment]
Sorry, i can't get you. Would you mind give more details? Why after reversing, the problem will be easier. Thx.

**Comment by gzc** [comment]
我当初这样做大概是因为,如果直接跑radix sort需要有对字符串"补齐"之类的操作,"ab" 排在 "abcd" 前面就需要给"ab"添加2个特殊字符.如果先reverse,就能用radix sort进行分而治之.. 不reverse也没关系从前面往后面扫描分而治之. 如果你有更好的想法可以提供一下哈^^

**Comment by Soyn** [comment]
I think this url is a good solution, but coding is too complicated. If you think this okay, I can pull this solution later. Moreover if you Don't you mind, can you give me a star to [my repository](https://github.com/Soyn/sicp) , and can you give me a link to how to learn Latex like you do before. I have already found some links in google, but they didn't work in github. Thx a lot.

**Comment by Soyn** [comment]
And do you have a Wechat, maybe we can talk more in Wechat. This is my id of wechat: w604408482

**Comment by gzc** [comment]
ok, i have starred

**Comment by Soyn** [comment]
Sorry for foget  the URl. It's [here](http://clrs.skanev.com/08/problems/04.html)

**Comment by Soyn** [comment]
Above is a wrong url, Plz forgive me, look [this](http://clrs.skanev.com/08/problems/03.html)
